---
  - name: Create WordPress deployment directory
    file:
      path: /srv/www
      owner: www-data
      state: directory

  - name: Downloading WordPress
    shell: |
      curl https://wordpress.org/latest.tar.gz | sudo -u www-data tar zx -C /srv/www

  - name: copy wordpress.conf into apache2 sites-available
    copy:
      src: wordpress.conf
      dest: /etc/apache2/sites-available/000-default.conf

  - name: update WordPress config
    ansible.builtin.template:
      src: wp-config.php.j2
      dest: "{{config_dest}}"
      owner: www-data
      group: www-data
    notify: Restart apache2

  - name: copy wordpress.conf into apache2 sites-enabled
    copy:
      src: wordpress.conf
      dest: /etc/apache2/sites-enabled/000-default.conf

  - name: Enable rewrite module
    community.general.apache2_module:
      state: present
      name: rewrite
    notify: Restart apache2

  - name: Enable wordpress module
    shell: |
      sudo a2ensite wordpress
    notify: Restart apache2
      
  - name: Create a database of name wordpress
    mysql_db:
      name: wordpress
      state: present
      login_unix_socket: /run/mysqld/mysqld.sock

  - name: Create an user named wordpress
    mysql_user:
      name: wordpress
      password: test
      priv:
        'wordpress.*': 'SELECT,INSERT,UPDATE,DELETE,CREATE,DROP,ALTER'
      state: present
    become: yes
